### PR TITLE
Added support for Swedish

### PR DESCRIPTION
**Pull request by Najoj**

### CODE REVIEW

**Comment by Synzvato** [comment]
Thanks for contributing! Since you speak Swedish, if you'd like to translate other aspects of the project as well, I would happily add Swedish as a target language to Decentraleyes' [translation project](https://crowdin.com/project/decentraleyes).

**Comment by Najoj** [comment]
Don't mention it! I have been translating a few projects on Crowdin before, so go ahead. I would love to contribute.

**Comment by Synzvato** [comment]
Awesome! I have just used your other translations to localize the [add-on download page](https://addons.mozilla.org/sv-SE/firefox/addon/decentraleyes/).

**Comment by Najoj** [comment]
Great. Looks nice.

**Pull request merged**
