### PR TITLE
Implement support for Pale Moon v27.1 and higher

### LINKED ISSUE #119: The latest release is incompatible with Pale Moon 27
First, thanks for your addon and for Pale Moon support!

Unfortunately your addon doesn't work with Pale Moon 27. I can open the option window and it can be installed but it doesn't work - testet with your testsite.

Pale Moon 27 is currently in alpha stage but if you can get it work again, then that would be awesome!
Here you can get the new version: https://www.palemoon.org/WIP/

Ah the reason is probably your addon is a jetpack addon, right? Pale Moon 27+ doesn't support Jetpack addons.

### PR DESCRIPTION
**Pull request by JustOff**
Based on [PMkit documentation draft v1.1](https://github.com/JustOff/pm27-sdk-addons/blob/master/PMkit.md), tested with [Pale Moon 27.1.0b1](http://www.palemoon.org/unstable/).

Resolves #119.

### CODE REVIEW

**Comment by Synzvato** [comment]
Thanks for testing this, and for committing the results. Much appreciated!

**Comment by JustOff** [comment]
Thank you for supporting Pale Moon!

**Comment by beerisgood** [comment]
Thanks!

**Comment by JustOff** [comment]
Could you please update https://addons.palemoon.org/extensions/decentraleyes/ with new version?

**Comment by Synzvato** [comment]
@JustOff I have added Pale Moon builds of ```v1.3.6``` and ```v1.3.7``` to the list of [add-on releases](https://github.com/Synzvato/decentraleyes/releases). I cannot directly submit new add-on releases to ```palemoon.org```, but I'll be sure to file a request.

**Comment by beerisgood** [comment]
Decentraleyes.v1.3.7-palemoon-unsigned.xpi works nativ with Pale Moon 27.1
Good work guys!

**Comment by JustOff** [comment]
@Synzvato Thank you very much!

@Lootyhoof please note, that author of Decentraleyes have no access to ftp@addons.palemoon.org, I hope you can help to resolve this.

**Comment by Lootyhoof** [comment]
@Synzvato Do you have a more private method of communication I could provide some details to?

**Comment by Lootyhoof** [comment]
@Synzvato Never mind, I forgot you had a forum account. 😅 I'll send you the details via PM shortly.

In the meantime I've updated the listing for you.

**Comment by Synzvato** [comment]
> Thank you very much!

@JustOff You're very welcome, and many thanks for making this possible.

> Never mind, I forgot you had a forum account. [...] I'll send you the details via PM shortly [...] In the meantime I've updated the listing for you.

@Lootyhoof Thanks for updating the listing, and I look forward to receiving the credentials!

**Pull request merged**
