### PR TITLE
Misc README enhancements to improve readability

### PR DESCRIPTION
**Pull request by Gitoffthelawn**

### CODE REVIEW

**Comment by solt87** [comment]
:+1: 

English is a second language to me, but this pull request seems "legit" to me.

**Comment by war59312** [comment]
Yes it's fine.

**Comment by abunasersaifullah** [comment]
Feedback

**Comment by Synzvato** [comment]
As you might have noticed, the ```README``` has undergone a major rewrite. I have managed to incorporate a couple of the suggestions into the new document. Thanks for taking the time to contribute!

**Pull request closed without merging**
