### PR TITLE
Optimize application icon compression

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Lossless recompression using Google's zopflipng.
```
 icon.png   | Bin 12135 -> 2816 bytes
 icon64.png | Bin 19333 -> 3780 bytes
```

### CODE REVIEW

**Comment by Gitoffthelawn** [comment]
Thanks @PeterDaveHello 

Is there any decompression processing cost greater than the current compression?

**Comment by austinhartzheim** [comment]
@Gitoffthelawn I was curious myself. Wikipedia cites [this study](http://aq.hao124.eu.org/files/d7471e59937ee9ac-u-AHR0cHM6Ly96b3BmbGkUZ29vZ2xlY29kZs5jb20vZmlSZXMvRGf0YV9jb21wcmVzc2lvbl91c2lUZ19Ab3BmbGkUcGRm.pdf) which says that "decompression speed of Zopfli-generated output is comparable with other algorithms."

**Comment by PeterDaveHello** [comment]
@Gitoffthelawn same same, as @austinhartzheim mentioned document says.

**Comment by Gitoffthelawn** [comment]
@austinhartzheim @PeterDaveHello Thanks thanks!

**Comment by Synzvato** [comment]
@PeterDaveHello Thanks for your contribution!

I have performed a quick test to find out by how much this reduces the add-on size. The  size difference between the zopfli icons and the originals appears to be ~7.3 KB after add-on compilation.

Add-on State | Difference
:--------|:-----------
Uncompressed | 24872 bytes
Packaged _(xpi)_ | 7297 bytes

So, since it's a bit smaller, and since the decompression speed is comparable with other algorithms, I think replacing the current icons is a good idea. Thanks again for looking into this!

**Pull request merged**
